apiVersion: v1
kind: Service
metadata:
  name: gridsight-ui
  namespace: gridsight
spec:
  type: ClusterIP

  selector:
    app: gridsight-ui

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8501
