apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Streamlit UI
  - streamlit/namespace.yaml
  - streamlit/deployment.yaml
  - streamlit/service.yaml

  # KServe
  - kserve/inference.yaml
